pipeline{
    agent {
        label "Jenkins_agent"
    }
    parameters {
        choice( name: 'action', choices: ['apply', 'destroy'], description: 'select action' )
    }
    stages {
        stage("01-vpc") {
            steps {
                sh """
                    cd 01-vpc
                    terraform init
                    terraform plan
                    terraform ${params.action} -auto-approve
                """
            }
        }
        stage("02-sg") {
            steps {
                sh """
                    cd 02-sg
                    terraform init
                    terraform plan
                    terraform ${params.action} -auto-approve
                """
            }
        }
        stage("04-databases") {
            steps {
                sh """
                    cd 04-databases
                    terraform init
                    terraform plan
                    terraform ${params.action} -auto-approve
                """
            }
        }
    }
    post{
        success{
            echo "pipeline is success"
        }
        failure{
            echo "pipline is failure"
        }
    }
}
