pipeline {
    agent {
        label "Jenkins_agent"
    }
    parameters {
        choice(name: 'action', choices: ['apply', 'destroy'], description: 'select action')
    }
    stages {
        stage("init stage") {
            steps {
                sh """
                    cd 02-sg
                    terraform init
                """
            }
        }
        stage("plan stage") {
            steps {
                sh """
                    cd 02-sg
                    terraform plan
                """
            }
        }
        stage("execute stage") {
            when {
                expression {
                    params.action == "${params.action}"
                }
            }
            steps {
                sh """
                    cd 02-sg
                    terraform "${params.action}" -auto-approve
                """
            }
        }
    }
    post {
        success{
            echo "pipeline is success"
        }
        failure{
            echo "pipeline is failure"
        }
    }
}